// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"
	"log/slog"

	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/config"
	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/domain"
	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/repository/postgres"
	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/transport/searchClient"
	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/transport/stateClient"
	"github.com/ReilEgor/Vaca/services/DataProcessorService/internal/usecase"
	"github.com/google/wire"
)

import (
	_ "github.com/ReilEgor/Vaca/pkg"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, dsn string, rabbitURL config.RabbitURL, qSubscriberName config.SubscriberQueueName, logger *slog.Logger, stateClientAddr config.StateClientAddr, searchClientAddr config.SearchClientAddr, qPublisherName config.PublisherQueueName) (*App, func(), error) {
	stateClientStateClient := stateClient.NewStateClient(stateClientAddr)
	pool, cleanup, err := postgres.NewPostgresDB(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	vacancyRepository := postgres.NewVacancyRepository(pool)
	searchClientSearchClient := searchClient.NewSearchClient(searchClientAddr)
	connection, cleanup2, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	channel, cleanup3, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	dataPublisher := rabbitmq.NewDataPublisher(channel, qPublisherName)
	dataProcessorInteractor := usecase.NewDataProcessorInteractor(stateClientStateClient, vacancyRepository, searchClientSearchClient, dataPublisher)
	dataSubscriber := rabbitmq.NewTaskSubscriber(channel, dataProcessorInteractor, logger, qSubscriberName)
	app := &App{
		Logic:      dataProcessorInteractor,
		Repository: vacancyRepository,
		Subscriber: dataSubscriber,
		SearchRepo: searchClientSearchClient,
	}
	return app, func() {
		cleanup3()
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewDataProcessorInteractor, wire.Bind(new(domain.DataProcessorUsecase), new(*usecase.DataProcessorInteractor)))

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewTaskSubscriber, rabbitmq.NewDataPublisher, wire.Bind(new(domain.DataPublisher), new(*rabbitmq.DataPublisher)), wire.Bind(new(domain.DataSubscriber), new(*rabbitmq.DataSubscriber)))

var RepositorySet = wire.NewSet(postgres.NewPostgresDB, postgres.NewVacancyRepository)

var SearchClientSet = wire.NewSet(searchClient.NewSearchClient, wire.Bind(new(domain.SearchRepository), new(*searchClient.SearchClient)))

var StateClientSet = wire.NewSet(stateClient.NewStateClient, wire.Bind(new(domain.StateRepository), new(*stateClient.StateClient)))

type App struct {
	Logic      domain.DataProcessorUsecase
	Repository domain.VacancyRepository
	Subscriber domain.DataSubscriber
	SearchRepo domain.SearchRepository
}
