// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/Vaca/services/SearchService/api/proto/gen/elastic"
	"github.com/ReilEgor/Vaca/services/SearchService/internal/config"
	"github.com/ReilEgor/Vaca/services/SearchService/internal/domain"
	"github.com/ReilEgor/Vaca/services/SearchService/internal/repository/elasticsearch"
	"github.com/ReilEgor/Vaca/services/SearchService/internal/transport/grpc"
	"github.com/ReilEgor/Vaca/services/SearchService/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(searchRepoURL config.ElasticSearchURL, grpcPort config.GRPCPort) (*App, func(), error) {
	typedClient, err := elasticsearch.NewElasticClient(searchRepoURL)
	if err != nil {
		return nil, nil, err
	}
	searchRepository := elasticsearch.NewElasticRepository(typedClient)
	searchInteractor := usecase.NewSearchUsecase(searchRepository)
	searchHandler := grpc.NewSearchHandler(searchInteractor)
	server := grpc.NewServer(grpcPort, searchHandler)
	app := &App{
		Repository: searchRepository,
		Server:     server,
	}
	return app, func() {
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewSearchUsecase, wire.Bind(new(domain.SearchUsecase), new(*usecase.SearchInteractor)))

var GRPCSet = wire.NewSet(grpc.NewSearchHandler, grpc.NewServer, wire.Bind(new(elasticv1.SearchServiceServer), new(*grpc.SearchHandler)))

var ElasticSet = wire.NewSet(elasticsearch.NewElasticClient, elasticsearch.NewElasticRepository)

type App struct {
	Repository domain.SearchRepository
	Server     *grpc.Server
}
