basePath: /api/v1
consumes:
- application/json
definitions:
  internal_transport_rest_handlers.CreateTaskRequest:
    properties:
      keywords:
        items:
          type: string
        type: array
      sources:
        items:
          type: string
        type: array
    required:
    - keywords
    - sources
    type: object
  internal_transport_rest_handlers.CreateTaskResponse:
    properties:
      created_at:
        type: string
      status:
        type: string
      task_id:
        type: string
    required:
    - created_at
    - status
    - task_id
    type: object
  internal_transport_rest_handlers.ListSourcesResponse:
    properties:
      sources:
        items:
          $ref: '#/definitions/internal_transport_rest_handlers.SourceResponse'
        type: array
      total:
        minimum: 0
        type: integer
    required:
    - sources
    - total
    type: object
  internal_transport_rest_handlers.SearchVacanciesResponse:
    properties:
      items:
        items:
          $ref: '#/definitions/internal_transport_rest_handlers.VacancyResponse'
        type: array
      total:
        minimum: 0
        type: integer
    required:
    - items
    - total
    type: object
  internal_transport_rest_handlers.SourceResponse:
    properties:
      id:
        example: "1"
        type: string
      name:
        example: Dou.ua
        type: string
    required:
    - id
    - name
    type: object
  internal_transport_rest_handlers.VacancyResponse:
    properties:
      about:
        type: string
      company:
        type: string
      description:
        type: string
      id:
        type: string
      link:
        type: string
      location:
        type: string
      requirements:
        type: string
      salary:
        type: string
      title:
        minLength: 3
        type: string
    required:
    - about
    - company
    - id
    - link
    - requirements
    - title
    type: object
host: localhost:8080
info:
  contact:
    name: Egor Reil
    url: https://github.com/ReilEgor
  description: This is the Coordinator Service for the Vaca project.
  termsOfService: http://swagger.io/terms/
  title: Coordinator Service API
  version: "1.0"
paths:
  /sources:
    get:
      consumes:
      - application/json
      description: Returns a list of all available data sources including their IDs
        and names
      produces:
      - application/json
      responses:
        "200":
          description: Successful response with source list
          schema:
            $ref: '#/definitions/internal_transport_rest_handlers.ListSourcesResponse'
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get available sources
      tags:
      - sources
  /tasks:
    post:
      consumes:
      - application/json
      description: Submit keywords and sources to initiate a new background task
      parameters:
      - description: Task Creation Details
        in: body
        name: request
        required: true
        schema:
          $ref: '#/definitions/internal_transport_rest_handlers.CreateTaskRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/internal_transport_rest_handlers.CreateTaskResponse'
        "400":
          description: Invalid request body
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Create a new processing task
      tags:
      - tasks
  /tasks/{id}:
    get:
      consumes:
      - application/json
      description: Retrieve the current processing status and metadata for a task
        by its UUID
      parameters:
      - description: Task ID (UUID)
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_handlers.CreateTaskResponse'
        "400":
          description: Task ID is required
          schema:
            additionalProperties:
              type: string
            type: object
        "404":
          description: Task not found
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Get status of a specific task
      tags:
      - tasks
  /vacancies:
    get:
      consumes:
      - application/json
      description: Retrieve a paginated list of vacancies based on filters like title,
        company, or location
      parameters:
      - in: query
        name: limit
        type: integer
      - in: query
        name: location
        type: string
      - in: query
        name: offset
        type: integer
      - in: query
        name: query
        type: string
      - in: query
        name: requirements
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_transport_rest_handlers.SearchVacanciesResponse'
        "400":
          description: Invalid query parameters
          schema:
            additionalProperties:
              type: string
            type: object
        "500":
          description: Internal server error
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Search and filter vacancies
      tags:
      - vacancies
produces:
- application/json
schemes:
- http
- https
swagger: "2.0"
