// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/Vaca/services/StateService/api/proto/gen/task_state"
	"github.com/ReilEgor/Vaca/services/StateService/internal/config"
	"github.com/ReilEgor/Vaca/services/StateService/internal/domain"
	"github.com/ReilEgor/Vaca/services/StateService/internal/repository/redis"
	"github.com/ReilEgor/Vaca/services/StateService/internal/transport/grpc"
	"github.com/ReilEgor/Vaca/services/StateService/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(host config.Host, redisPort config.RedisPort, password config.Password, db config.DB, grpcPort config.GRPCPort) (*App, func(), error) {
	client, err := redis.NewRedisClient(host, redisPort, password, db)
	if err != nil {
		return nil, nil, err
	}
	stateRepository := redis.NewRedisTokenRepository(client)
	taskInteractor := usecase.NewTaskUsecase(stateRepository)
	taskStateHandler := grpc.NewTaskStateHandler(taskInteractor)
	server := grpc.NewServer(grpcPort, taskStateHandler)
	app := &App{
		Repository: stateRepository,
		Server:     server,
	}
	return app, func() {
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewTaskUsecase, wire.Bind(new(domain.StateUsecase), new(*usecase.TaskInteractor)))

var GRPCSet = wire.NewSet(grpc.NewTaskStateHandler, grpc.NewServer, wire.Bind(new(task_statev1.TaskStateServiceServer), new(*grpc.TaskStateHandler)))

var RedisSet = wire.NewSet(redis.NewRedisClient, redis.NewRedisTokenRepository)

type App struct {
	Repository domain.StateRepository
	Server     *grpc.Server
}
