// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/domain"
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/usecase"
	"github.com/google/wire"
	"log/slog"
)

import (
	_ "github.com/ReilEgor/Vaca/pkg"
)

// Injectors from wire.go:

func InitializeApp(rabbitURL rabbitmq.RabbitURL, qName rabbitmq.SubscriberQueueName, rKey rabbitmq.SubscriberRoutingKey, exch rabbitmq.SubscriberExchange, logger *slog.Logger) (*App, func(), error) {
	douInteractor := usecase.NewDouInteractor()
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	taskSubscriber := rabbitmq.NewTaskSubscriber(channel, douInteractor, logger, qName, rKey, exch)
	app := &App{
		Logic:      douInteractor,
		Subscriber: taskSubscriber,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewDouInteractor, wire.Bind(new(domain.ScraperUsecase), new(*usecase.DouInteractor)))

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewTaskSubscriber, wire.Bind(new(domain.TaskSubscriber), new(*rabbitmq.TaskSubscriber)))

type App struct {
	Logic      domain.ScraperUsecase
	Subscriber domain.TaskSubscriber
}
