// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"log/slog"

	"github.com/ReilEgor/Vaca/services/DouScraper/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/config"
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/domain"
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/transport/stateClient"
	"github.com/ReilEgor/Vaca/services/DouScraper/internal/usecase"
	"github.com/google/wire"
)

import (
	_ "github.com/ReilEgor/Vaca/pkg"
)

// Injectors from wire.go:

func InitializeApp(rabbitURL rabbitmq.RabbitURL, qName rabbitmq.SubscriberQueueName, rKey rabbitmq.SubscriberRoutingKey, exch rabbitmq.SubscriberExchange, publishQName rabbitmq.PublisherQueueName, logger *slog.Logger, stateClientAddr config.StateClientAddr) (*App, func(), error) {
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher := rabbitmq.NewPublisher(channel, publishQName)
	douInteractor := usecase.NewDouInteractor(publisher)
	taskSubscriber := rabbitmq.NewTaskSubscriber(channel, douInteractor, logger, qName, rKey, exch)
	stateClientStateClient := stateClient.NewStateClient(stateClientAddr)
	app := &App{
		Logic:      douInteractor,
		Subscriber: taskSubscriber,
		Repository: stateClientStateClient,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewDouInteractor, wire.Bind(new(domain.ScraperUsecase), new(*usecase.DouInteractor)))

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewPublisher, rabbitmq.NewTaskSubscriber, wire.Bind(new(domain.TaskSubscriber), new(*rabbitmq.TaskSubscriber)), wire.Bind(new(domain.ResultPublisher), new(*rabbitmq.Publisher)))

var StateClientSet = wire.NewSet(stateClient.NewStateClient)

type App struct {
	Logic      domain.ScraperUsecase
	Subscriber domain.TaskSubscriber
	Repository *stateClient.StateClient
}
