// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pkg "github.com/ReilEgor/Vaca/pkg"

	uuid "github.com/google/uuid"
)

// CoordinatorUsecase is an autogenerated mock type for the CoordinatorUsecase type
type CoordinatorUsecase struct {
	mock.Mock
}

// CreateTask provides a mock function with given fields: ctx, keywords, sources
func (_m *CoordinatorUsecase) CreateTask(ctx context.Context, keywords []string, sources []string) (*uuid.UUID, error) {
	ret := _m.Called(ctx, keywords, sources)

	if len(ret) == 0 {
		panic("no return value specified for CreateTask")
	}

	var r0 *uuid.UUID
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) (*uuid.UUID, error)); ok {
		return rf(ctx, keywords, sources)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string, []string) *uuid.UUID); ok {
		r0 = rf(ctx, keywords, sources)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*uuid.UUID)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string, []string) error); ok {
		r1 = rf(ctx, keywords, sources)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAvailableSources provides a mock function with given fields: ctx
func (_m *CoordinatorUsecase) GetAvailableSources(ctx context.Context) ([]pkg.Source, int64, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetAvailableSources")
	}

	var r0 []pkg.Source
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]pkg.Source, int64, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []pkg.Source); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) int64); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context) error); ok {
		r2 = rf(ctx)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// GetTaskStatus provides a mock function with given fields: ctx, taskID
func (_m *CoordinatorUsecase) GetTaskStatus(ctx context.Context, taskID string) (*pkg.Task, error) {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for GetTaskStatus")
	}

	var r0 *pkg.Task
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*pkg.Task, error)); ok {
		return rf(ctx, taskID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *pkg.Task); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pkg.Task)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, taskID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetVacancies provides a mock function with given fields: ctx, filter
func (_m *CoordinatorUsecase) GetVacancies(ctx context.Context, filter pkg.VacancyFilter) ([]*pkg.Vacancy, int64, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for GetVacancies")
	}

	var r0 []*pkg.Vacancy
	var r1 int64
	var r2 error
	if rf, ok := ret.Get(0).(func(context.Context, pkg.VacancyFilter) ([]*pkg.Vacancy, int64, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pkg.VacancyFilter) []*pkg.Vacancy); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkg.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pkg.VacancyFilter) int64); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Get(1).(int64)
	}

	if rf, ok := ret.Get(2).(func(context.Context, pkg.VacancyFilter) error); ok {
		r2 = rf(ctx, filter)
	} else {
		r2 = ret.Error(2)
	}

	return r0, r1, r2
}

// NewCoordinatorUsecase creates a new instance of CoordinatorUsecase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCoordinatorUsecase(t interface {
	mock.TestingT
	Cleanup(func())
}) *CoordinatorUsecase {
	mock := &CoordinatorUsecase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
