// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pkg "github.com/ReilEgor/Vaca/pkg"

	time "time"
)

// StatusRepository is an autogenerated mock type for the StatusRepository type
type StatusRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, taskID
func (_m *StatusRepository) Get(ctx context.Context, taskID string) map[string]string {
	ret := _m.Called(ctx, taskID)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 map[string]string
	if rf, ok := ret.Get(0).(func(context.Context, string) map[string]string); ok {
		r0 = rf(ctx, taskID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]string)
		}
	}

	return r0
}

// GetIDByHash provides a mock function with given fields: ctx, searchKey
func (_m *StatusRepository) GetIDByHash(ctx context.Context, searchKey string) (string, error) {
	ret := _m.Called(ctx, searchKey)

	if len(ret) == 0 {
		panic("no return value specified for GetIDByHash")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (string, error)); ok {
		return rf(ctx, searchKey)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, searchKey)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, searchKey)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetSources provides a mock function with given fields: ctx
func (_m *StatusRepository) GetSources(ctx context.Context) ([]pkg.Source, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetSources")
	}

	var r0 []pkg.Source
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]pkg.Source, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []pkg.Source); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]pkg.Source)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Set provides a mock function with given fields: ctx, taskID, searchKey, totalSources, ttl
func (_m *StatusRepository) Set(ctx context.Context, taskID string, searchKey string, totalSources int, ttl time.Duration) error {
	ret := _m.Called(ctx, taskID, searchKey, totalSources, ttl)

	if len(ret) == 0 {
		panic("no return value specified for Set")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int, time.Duration) error); ok {
		r0 = rf(ctx, taskID, searchKey, totalSources, ttl)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewStatusRepository creates a new instance of StatusRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewStatusRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *StatusRepository {
	mock := &StatusRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
