// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pkg "github.com/ReilEgor/Vaca/pkg"
)

// TaskPublisher is an autogenerated mock type for the TaskPublisher type
type TaskPublisher struct {
	mock.Mock
}

// PublishTask provides a mock function with given fields: ctx, taskMessage, routingKey
func (_m *TaskPublisher) PublishTask(ctx context.Context, taskMessage pkg.ScrapeTask, routingKey string) error {
	ret := _m.Called(ctx, taskMessage, routingKey)

	if len(ret) == 0 {
		panic("no return value specified for PublishTask")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, pkg.ScrapeTask, string) error); ok {
		r0 = rf(ctx, taskMessage, routingKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewTaskPublisher creates a new instance of TaskPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTaskPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *TaskPublisher {
	mock := &TaskPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
