// Code generated by mockery v2.53.5. DO NOT EDIT.

package domain

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	pkg "github.com/ReilEgor/Vaca/pkg"
)

// VacancySearchRepository is an autogenerated mock type for the VacancySearchRepository type
type VacancySearchRepository struct {
	mock.Mock
}

// Search provides a mock function with given fields: ctx, filter
func (_m *VacancySearchRepository) Search(ctx context.Context, filter pkg.VacancyFilter) ([]*pkg.Vacancy, error) {
	ret := _m.Called(ctx, filter)

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []*pkg.Vacancy
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, pkg.VacancyFilter) ([]*pkg.Vacancy, error)); ok {
		return rf(ctx, filter)
	}
	if rf, ok := ret.Get(0).(func(context.Context, pkg.VacancyFilter) []*pkg.Vacancy); ok {
		r0 = rf(ctx, filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*pkg.Vacancy)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, pkg.VacancyFilter) error); ok {
		r1 = rf(ctx, filter)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewVacancySearchRepository creates a new instance of VacancySearchRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewVacancySearchRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *VacancySearchRepository {
	mock := &VacancySearchRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
