// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/config"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/domain"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/repository/elasticsearch"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/repository/redis"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/rest"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/rest/handlers"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/usecase"
	"github.com/google/wire"
)

import (
	_ "github.com/ReilEgor/Vaca/pkg"
)

// Injectors from wire.go:

func InitializeApp(rabbitURL rabbitmq.RabbitURL, searchRepoURL elasticsearch.ElasticSearchURL, taskQueue rabbitmq.PublisherQueueName) (*App, func(), error) {
	configConfig := config.NewConfig()
	client, err := redis.NewRedisClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	statusRepository := redis.NewRedisTokenRepository(client)
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher := rabbitmq.NewPublisher(channel, taskQueue)
	typedClient, err := elasticsearch.NewElasticClient(searchRepoURL)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	elasticRepository := elasticsearch.NewElasticRepository(typedClient)
	coordinatorInteractor := usecase.NewCoordinatorUsecase(statusRepository, publisher, elasticRepository)
	ginServer := rest.NewGinServer(coordinatorInteractor)
	app := &App{
		Logic:      coordinatorInteractor,
		Server:     ginServer,
		Repository: statusRepository,
		SearchRepo: elasticRepository,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewCoordinatorUsecase, wire.Bind(new(domain.CoordinatorUsecase), new(*usecase.CoordinatorInteractor)))

var RestSet = wire.NewSet(rest.NewGinServer, handler.NewHandler)

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewPublisher, wire.Bind(new(domain.TaskPublisher), new(*rabbitmq.Publisher)))

var InfraSet = wire.NewSet(config.NewConfig, redis.NewRedisClient, redis.NewRedisTokenRepository)

type App struct {
	Logic      domain.CoordinatorUsecase
	Server     *rest.GinServer
	Repository domain.StatusRepository
	SearchRepo domain.VacancySearchRepository
}

var ElasticSet = wire.NewSet(elasticsearch.NewElasticClient, elasticsearch.NewElasticRepository, wire.Bind(new(domain.VacancySearchRepository), new(*elasticsearch.ElasticRepository)))
