// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/config"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/domain"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/repository/elasticsearch"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/rest"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/rest/handlers"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/stateClient"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/usecase"
	"github.com/google/wire"
)

import (
	_ "github.com/ReilEgor/Vaca/pkg"
)

// Injectors from wire.go:

func InitializeApp(rabbitURL rabbitmq.RabbitURL, searchRepoURL elasticsearch.ElasticSearchURL, taskQueue rabbitmq.PublisherQueueName, stateClientAddr config.StateClientAddr) (*App, func(), error) {
	stateClientStateClient := stateClient.NewStateClient(stateClientAddr)
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher := rabbitmq.NewPublisher(channel, taskQueue)
	typedClient, err := elasticsearch.NewElasticClient(searchRepoURL)
	if err != nil {
		cleanup2()
		cleanup()
		return nil, nil, err
	}
	elasticRepository := elasticsearch.NewElasticRepository(typedClient)
	coordinatorInteractor := usecase.NewCoordinatorUsecase(stateClientStateClient, publisher, elasticRepository)
	ginServer := rest.NewGinServer(coordinatorInteractor)
	app := &App{
		Logic:      coordinatorInteractor,
		Server:     ginServer,
		SearchRepo: elasticRepository,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewCoordinatorUsecase, wire.Bind(new(domain.CoordinatorUsecase), new(*usecase.CoordinatorInteractor)))

var RestSet = wire.NewSet(rest.NewGinServer, handler.NewHandler)

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewPublisher, wire.Bind(new(domain.TaskPublisher), new(*rabbitmq.Publisher)))

var ElasticSet = wire.NewSet(elasticsearch.NewElasticClient, elasticsearch.NewElasticRepository, wire.Bind(new(domain.VacancySearchRepository), new(*elasticsearch.ElasticRepository)))

var StateClient = wire.NewSet(stateClient.NewStateClient)

type App struct {
	Logic      domain.CoordinatorUsecase
	Server     *rest.GinServer
	SearchRepo domain.VacancySearchRepository
}
