// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/config"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/domain"
	redis2 "github.com/ReilEgor/Vaca/services/CoordinatorService/internal/repository/redis"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/rest"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/transport/rest/handlers"
	"github.com/ReilEgor/Vaca/services/CoordinatorService/internal/usecase"
	"github.com/google/wire"
)

import (
	_ "github.com/ReilEgor/Vaca/pkg"
)

// Injectors from wire.go:

func InitializeApp(rabbitURL rabbitmq.RabbitURL, taskQueue rabbitmq.PublisherQueueName) (*App, func(), error) {
	configConfig := config.NewConfig()
	client, err := redis2.NewRedisClient(configConfig)
	if err != nil {
		return nil, nil, err
	}
	statusRepository := redis2.NewRedisTokenRepository(client)
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	publisher := rabbitmq.NewPublisher(channel, taskQueue)
	coordinatorInteractor := usecase.NewCoordinatorUsecase(statusRepository, publisher)
	ginServer := rest.NewGinServer(coordinatorInteractor)
	app := &App{
		Logic:      coordinatorInteractor,
		Server:     ginServer,
		Repository: statusRepository,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewCoordinatorUsecase, wire.Bind(new(domain.CoordinatorUsecase), new(*usecase.CoordinatorInteractor)))

var RestSet = wire.NewSet(rest.NewGinServer, handler.NewHandler)

var BrokerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewPublisher, wire.Bind(new(domain.TaskPublisher), new(*rabbitmq.Publisher)))

var InfraSet = wire.NewSet(config.NewConfig, redis2.NewRedisClient, redis2.NewRedisTokenRepository)

type App struct {
	Logic      domain.CoordinatorUsecase
	Server     *rest.GinServer
	Repository domain.StatusRepository
}
