// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"context"

	"github.com/ReilEgor/Vaca/services/NotificationService/internal/broker/rabbitmq"
	"github.com/ReilEgor/Vaca/services/NotificationService/internal/config"
	"github.com/ReilEgor/Vaca/services/NotificationService/internal/domain"
	"github.com/ReilEgor/Vaca/services/NotificationService/internal/usecase"
	"github.com/google/wire"
)

// Injectors from wire.go:

func InitializeApp(ctx context.Context, rabbitURL config.RabbitMQURL, qName config.SubscriberQueueName) (*App, func(), error) {
	connection, cleanup, err := rabbitmq.NewRabbitMQConn(rabbitURL)
	if err != nil {
		return nil, nil, err
	}
	channel, cleanup2, err := rabbitmq.NewRabbitMQChannel(connection)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	notificationUsecase := usecase.NewNotificationUsecase()
	notificationSubscriber := rabbitmq.NewNotificationSubscriber(channel, notificationUsecase, qName)
	app := &App{
		listener: notificationSubscriber,
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}

// wire.go:

var UsecaseSet = wire.NewSet(usecase.NewNotificationUsecase, wire.Bind(new(domain.NotificationUsecase), new(*usecase.NotificationUsecase)))

var ListenerSet = wire.NewSet(rabbitmq.NewRabbitMQConn, rabbitmq.NewRabbitMQChannel, rabbitmq.NewNotificationSubscriber, wire.Bind(new(domain.NotificationSubscriber), new(*rabbitmq.NotificationSubscriber)))

type App struct {
	listener domain.NotificationSubscriber
}
